### ISSUE TITLE
Could you release the pretrained model?

### ISSUE THREAD

**Issue by JackyChan97** [cxzhou95/XLSR#1]

**Comment by cxzhou95** [comment]
Ok, I will release them at this weekend.
ZhuojieChen ***@***.***>于2021年8月5日 周四下午9:13写道：

**Comment by JackyChan97** [comment]
Thank you

**Comment by cxzhou95** [comment]
@JackyChan97  I have uploaded the pre-trained model, please take a look. The performance (PSNR) of my implementation (x3 SR) on the DIV2K validation dataset is 30.092dB (30.10dB reported in the paper).
The performance of the quantized model (x3 SR) on the DIV2K validation dataset is 29.71dB (29.82dB reported in the paper). And I think this performance could be improved after I try different learning rates and training epochs.
However, I found the inference speed of XLSR's quantized model is slower than its float model because of pytorch framework (take too much time for the convolution when the number of channel is small, e.g., 8, 16, 32).

**Comment by JackyChan97** [comment]
Thank you so much, I will have a try.
